// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cost_grid.dart';
import 'course_detection.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pathfinding.dart';
import 'segmentation.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_map_impl`, `pick_demo_route_endpoints`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<AnalyzeResult> analyzeMap({
  required List<int> imageBytes,
  required List<ExcludeBox> legendBoxes,
  required double houghParam2,
  String? sourceFilename,
}) => RustLib.instance.api.crateApiAnalyzeAnalyzeMap(
  imageBytes: imageBytes,
  legendBoxes: legendBoxes,
  houghParam2: houghParam2,
  sourceFilename: sourceFilename,
);

/// Rebuilds the GeoJSON document from a (possibly hand-corrected) copy of
/// `segmentation`/`course` -- the manual-correction UI edits plain Dart-side
/// copies of those structs (add/move/delete a control or start/finish
/// marker, reclassify a terrain polygon's `class_name`), then calls this to
/// get an export that reflects the correction instead of the raw detection.
/// `route`/`route_terrain_breakdown` are passed through unchanged: this pass
/// of the correction UI doesn't recompute the cost grid or route from edited
/// terrain/controls yet (a deliberate scope cut, not an oversight -- see
/// `PHASE0_HANDOFF.md` on control-sequencing being separate follow-up work),
/// so a route already found against the original detection may no longer
/// reflect a moved control; the export is still geometrically the true
/// corrected map, it's only the route/terrain_breakdown properties that can
/// go stale after an edit that affects them.
Future<String> rebuildGeojson({
  required SegmentationResult segmentation,
  required CourseResult course,
  RouteResult? route,
  required List<TerrainFraction> routeTerrainBreakdown,
  required int width,
  required int height,
  required double scaleToOriginal,
  double? mnLineSpacingPx,
  required bool quadFound,
  required String sourceFilename,
}) => RustLib.instance.api.crateApiAnalyzeRebuildGeojson(
  segmentation: segmentation,
  course: course,
  route: route,
  routeTerrainBreakdown: routeTerrainBreakdown,
  width: width,
  height: height,
  scaleToOriginal: scaleToOriginal,
  mnLineSpacingPx: mnLineSpacingPx,
  quadFound: quadFound,
  sourceFilename: sourceFilename,
);

class AnalyzeResult {
  /// Rectified, white-balanced image, PNG-encoded.
  final Uint8List imagePng;
  final int width;
  final int height;
  final bool quadFound;
  final Float32List mnLineXs;
  final double? mnLineSpacingPx;
  final SegmentationResult segmentation;
  final CourseResult course;

  /// Demo route: there's no control-sequencing/course-graph yet
  /// (`course.controls` is an unordered list, matching the Python
  /// prototype's `CourseResult.controls`), so this is "start -> nearest
  /// control", or the first two detected controls if no start was found --
  /// a connectivity proof that the cost grid is pathable, not a real
  /// full-course route. `None` if neither condition is met (see
  /// `pick_demo_route_endpoints`).
  final RouteResult? route;

  /// What terrain `route` actually crossed, as a fraction of its length --
  /// empty if `route` is `None`. See `cost_grid::route_terrain_breakdown`.
  final List<TerrainFraction> routeTerrainBreakdown;

  /// This analysis, as a GeoJSON-shaped `FeatureCollection` string -- see
  /// `vectorize::build_geojson`. Write it straight to a `.geojson` file;
  /// there's no separate parsing step needed on the Dart side.
  final String geojson;

  const AnalyzeResult({
    required this.imagePng,
    required this.width,
    required this.height,
    required this.quadFound,
    required this.mnLineXs,
    this.mnLineSpacingPx,
    required this.segmentation,
    required this.course,
    this.route,
    required this.routeTerrainBreakdown,
    required this.geojson,
  });

  @override
  int get hashCode =>
      imagePng.hashCode ^
      width.hashCode ^
      height.hashCode ^
      quadFound.hashCode ^
      mnLineXs.hashCode ^
      mnLineSpacingPx.hashCode ^
      segmentation.hashCode ^
      course.hashCode ^
      route.hashCode ^
      routeTerrainBreakdown.hashCode ^
      geojson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyzeResult &&
          runtimeType == other.runtimeType &&
          imagePng == other.imagePng &&
          width == other.width &&
          height == other.height &&
          quadFound == other.quadFound &&
          mnLineXs == other.mnLineXs &&
          mnLineSpacingPx == other.mnLineSpacingPx &&
          segmentation == other.segmentation &&
          course == other.course &&
          route == other.route &&
          routeTerrainBreakdown == other.routeTerrainBreakdown &&
          geojson == other.geojson;
}
