// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_cost_grid`, `class_names`, `draw_lines_mask`, `fill_polygons_mask`, `route_terrain_breakdown`, `terrain_cost`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CostGridResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class TerrainFraction {
  final String className;
  final double fraction;

  const TerrainFraction({required this.className, required this.fraction});

  @override
  int get hashCode => className.hashCode ^ fraction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerrainFraction &&
          runtimeType == other.runtimeType &&
          className == other.className &&
          fraction == other.fraction;
}
