// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blank_disks`, `build_course_ink_mask`, `dedupe_finish`, `detect_controls`, `detect_course`, `detect_legs`, `detect_start_triangle`, `ring_ink_coverage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class Control {
  final double x;
  final double y;
  final double radius;

  /// OCR'd control code, e.g. "46" from a "7-46" label. Always `None` for
  /// now -- see module docs.
  final String? code;

  const Control({
    required this.x,
    required this.y,
    required this.radius,
    this.code,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ radius.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Control &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          radius == other.radius &&
          code == other.code;
}

class CourseResult {
  final List<Control> controls;
  final Pt? start;
  final Pt? finish;
  final List<Segment> legs;

  const CourseResult({
    required this.controls,
    this.start,
    this.finish,
    required this.legs,
  });

  static Future<CourseResult> default_() =>
      RustLib.instance.api.crateApiCourseDetectionCourseResultDefault();

  @override
  int get hashCode =>
      controls.hashCode ^ start.hashCode ^ finish.hashCode ^ legs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseResult &&
          runtimeType == other.runtimeType &&
          controls == other.controls &&
          start == other.start &&
          finish == other.finish &&
          legs == other.legs;
}
