// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Simplified polygon ring, exterior only (no holes) -- draft-quality, see
/// `segmentation` module docs for why this doesn't attempt shapely-style
/// polygon validity repair.
class Polygon {
  final List<Pt> points;

  const Polygon({required this.points});

  @override
  int get hashCode => points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Polygon &&
          runtimeType == other.runtimeType &&
          points == other.points;
}

class Pt {
  final double x;
  final double y;

  const Pt({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pt &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class Segment {
  final Pt a;
  final Pt b;

  const Segment({required this.a, required this.b});

  @override
  int get hashCode => a.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b;
}
