// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_route`, `geometric_path_cost`, `xy_to_rc`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HeapItem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `cmp`, `eq`, `fmt`, `partial_cmp`

class RouteResult {
  /// (x, y) pixel coords, image convention (Y-down).
  final List<Pt> points;
  final double cost;

  /// Independent cross-check on `cost`: a from-scratch resum of the same
  /// route against the same grid using the weighting documented above. If
  /// this drifts from `cost` by more than float rounding, something
  /// upstream is actually wrong, not just "approximate" -- same reasoning
  /// as the Python prototype's `RouteResult.recomputed_cost`.
  final double recomputedCost;

  const RouteResult({
    required this.points,
    required this.cost,
    required this.recomputedCost,
  });

  @override
  int get hashCode => points.hashCode ^ cost.hashCode ^ recomputedCost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteResult &&
          runtimeType == other.runtimeType &&
          points == other.points &&
          cost == other.cost &&
          recomputedCost == other.recomputedCost;
}
