// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `downscale`, `find_paper_quad`, `order_corners`, `point_dist`, `rectify_photo_impl`, `rectify`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<RectifyResult> rectifyPhoto({required List<int> imageBytes}) => RustLib
    .instance
    .api
    .crateApiPreprocessingRectifyPhoto(imageBytes: imageBytes);

class RectifyResult {
  /// Rectified (or, if no confident quad was found, merely downscaled)
  /// image, PNG-encoded.
  final Uint8List imagePng;

  /// False => paper-quad detection fell back to using the full frame.
  final bool quadFound;
  final int width;
  final int height;

  const RectifyResult({
    required this.imagePng,
    required this.quadFound,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      imagePng.hashCode ^ quadFound.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RectifyResult &&
          runtimeType == other.runtimeType &&
          imagePng == other.imagePng &&
          quadFound == other.quadFound &&
          width == other.width &&
          height == other.height;
}
