// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_valid_mask`, `classify_vegetation_cluster`, `hough_segments`, `marsh_mask`, `mask_to_polygons`, `out_of_bounds_mask`, `out_of_bounds_polygons`, `path_lines`, `rock_mask`, `scale_inplace`, `segment_terrain`, `water_mask`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

class ClassPolygons {
  final String className;
  final List<Polygon> polygons;

  const ClassPolygons({required this.className, required this.polygons});

  @override
  int get hashCode => className.hashCode ^ polygons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassPolygons &&
          runtimeType == other.runtimeType &&
          className == other.className &&
          polygons == other.polygons;
}

/// Fractional (x0, y0, x1, y1) box, in [0, 1] relative to the rectified
/// working-resolution image, to exclude from terrain classification (legend
/// tables, titles, sponsor logos). Caller-supplied, not a hardcoded per-file
/// table baked into this crate -- see `PHASE0_HANDOFF.md`'s explicit
/// guidance that the Python prototype's `config.LEGEND_EXCLUDE_BOXES`
/// doesn't generalize to a photo this repo hasn't seen and belongs behind
/// the manual-correction UI instead.
class ExcludeBox {
  final double x0;
  final double y0;
  final double x1;
  final double y1;

  const ExcludeBox({
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
  });

  @override
  int get hashCode => x0.hashCode ^ y0.hashCode ^ x1.hashCode ^ y1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExcludeBox &&
          runtimeType == other.runtimeType &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1;
}

class SegmentationResult {
  final List<ClassPolygons> polygonsByClass;
  final List<Segment> paths;

  const SegmentationResult({
    required this.polygonsByClass,
    required this.paths,
  });

  @override
  int get hashCode => polygonsByClass.hashCode ^ paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SegmentationResult &&
          runtimeType == other.runtimeType &&
          polygonsByClass == other.polygonsByClass &&
          paths == other.paths;
}
